FreshlyBakedCake/PacketMix

npins/sources.json
The nixos release [is nearly upon us!](https://github.com/NixOS/nixpkgs/issues/390768) and [channels were made yesterday](https://github.com/NixOS/infra/pull/687).
As we're preparing to add servers, now seems like a great time to stick ourselves to (the beta of) the upcoming stable release. We still expect to need some packages from unstable, so we can have that as a separate, non-default input like 24.11 was before
=> chore: switch nixos channel to 25.05

nilla.nix, npins/default.nix, npins/default.nix.license, npins/sources.json, systems/common/lix.nix, systems/personal/configuration.nix
[fix!: pin latest npins and lix](https://github.com/FreshlyBakedCake/PacketMix/commit/8727eb8f4fd8accbe32f98ed040823c9f86f54fa)
There was previously a lix bug where git inputs were constantly
refetched - this is fixed on lix main as long as you have the metadata
from npins v6
This commit doesn't update our metadata, but it does bump the lix and
npins versions to set the groundwork for this
BREAKING-CHANGE: This commit updates npins, breaking compatibility with npins v5 format
---
[chore!: upgrade npins metadata to v6](https://github.com/FreshlyBakedCake/PacketMix/commit/e1fbfbc7a27533089cc47e529112bc6db3c4f0de)
As we've upgraded npins, we need to update our sources.json to the new
version. Without this, we won't be able to change our pins
This also is the last piece needed to fix input …
=> fix!: pin latest npins and lix

homes/default.nix, homes/minion/ghostty.nix, homes/minion/zoxide.nix, nilla.nix, npins/sources.json, systems/default.nix, systems/personal/homes.nix
[feat: attach homes to systems](https://github.com/FreshlyBakedCake/PacketMix/commit/85416c372c421e0676b37724840f85ec853ec357)
I want to update homes with the existing OTA updates rather than
manually doing it. Attaching homes to systems with the new NixOS module
allows me to do this
This feature is currently unmerged in nilla-nix/home due to an aux lib
bug, so I've pinned the new home version as well as a nilla version to
update lib
=> feat: attach homes to systems

homes/default.nix, systems/common/inputs.nix, systems/common/lix.nix, systems/common/nilla-nix.nix, systems/default.nix, systems/personal/configuration.nix, systems/server/default.nix
This isn't a monorepo, so it doesn't make that much sense to call it monorepo- let's call it "project" instead
=> refactor: rename monorepo to project

homes/minion/niri.nix
Previously we had some random monitor positions - but it's nicer to have my work monitors correctly set-up. I will need a followup to fix my home monitors
Thankfully, niri now supports specifying monitors by serial/etc. so I can do this in a nicer way than messing with DP-foo to try to get everything to stay working
=> fix: correct work monitor positions

systems/default.nix, systems/javelin/default.nix, systems/javelin/udev.nix
Javelin is the firmware I use on my keyboard. I need these udev rules to configure it via the online tool at https://lim.au/
=> feat: add javelin udev rules

homes/default.nix, homes/minion/sd.nix
sd is a package that can do substitutions - in many ways it feels to sed what ripgrep is to grep. I would very much like to compose it with helix to have proper regex find/replace (i.e. by using '|sd ... ...' in helix)
=> feat: install sd

LICENSES/MPL-2.0.txt, homes/default.nix, homes/minion/helix.nix, nilla.nix, patches/helix/3958-labels-for-config-menus.patch, patches/helix/3958-labels-for-config-menus.patch.license
We've been using helix editor since the start but up until now it has only been in configuration.nix rather than getting config through home-manager. The config I've added here is a compilation of a couple of pieces of work...
- My currently-set options
- Some past config I had for some nice keybindings
Additionally, the keybinding piece also needs a long-awaited helix PR - we can just go ahead and patch that in
---
I've kept helix in configuration.nix too as I want to make sure that we still have a nice editor for, say, editing files as root/etc. Probably it should go in some file in "common" instead but that can be a followup
=> feat: add helix config

.github/workflows/npins-duplicate-check.yml
As it's possible to specify duplicate keys in npins, we need to route them out... Duplicated npins keys cause the earlier definition of a pin to be silently ignored, potentially causing confusion about what version is being used
=> ci: add check for duplicate npins keys

.github/workflows/nixos.yml
This check is quite expensive, so if we push new commits to a branch it is worth cancelling anything that is already running
=> ci: make nixos build run only once

homes/development/default.nix, homes/development/gpg.nix, systems/common/default.nix, systems/common/smartcard.nix
We can now use GPG to sign commits. This also enabled us to do so with yubikeys
=> feat(gpg): Enable GPG for signing

homes/default.nix, homes/remote/default.nix, homes/remote/ssh.nix
Without ssh-agent we are unable to ssh-add -K to import ssh keys from our yubikeys
=> feat(homes): add ssh-agent

homes/coded/appimage.nix, homes/coded/default.nix
I've added this so I can use Cider-2 using an AppImage as it is unfree software
=> feat(homes/coded): Add appimage-run

.github/workflows/eval.yml, homes/catppuccin/catppuccin.nix, homes/niri/niri.nix, systems/teal/hardware-configuration.nix
We will get evaluation warnings in two circumstances:
- We write some code that is doing something wrong
- Something gets deprecated in a routine npins bump
In either case we probably don't want to merge the breaking change - rather it would be nice to get notified so we can fix it
=> ci: ban evaluation warnings

homes/remote/ssh.nix
Previously we enabled the ssh-agent for users but didn't add any askpass command. This meant that if you were using a key that needed a pin it would immediately fail.
We can fix that by providing an SSH_ASKPASS environment variable to the service as it is started. Setting this for shells (e.g. via NixOS' programs.ssh.enableAskPassword) doesn't work as the agent never gets access to the set variable
=> fix(ssh-agent): add SSH_ASKPASS

homes/niri/niri.nix
Previously it was pretty hard to tell the difference between an unlocked computer on an empty desktop and a locked computer. This has caused me to accidentally leave my computer unlocked before.
After this change, the locked-ness becomes obvious as a glance!
=> feat(niri): grey lockscreen background

homes/niri/niri.nix
Niri has a rather neat "dynamic casting" feature where you can select a window/screen to be cast to a dynamic target (think like changing the window you are screen-sharing over Discord from your keybindings...).
I'd like to use this when screen recording in OBS, but it's unwieldy without any bindings. Therefore, let's add W and V (theoretically nmemonically for Window and Video) to set ... Windows and full monitor Videos to the dynamic target - these should be OK since as we don't use them for any other bindings and they make some sense.
=> feat(niri): Add dynamic casting binds

systems/default.nix, systems/espanso/default.nix, systems/espanso/espanso.nix, systems/espanso/nixpkgs-328890--espanso-capdacoverride/default.nix, systems/espanso/nixpkgs-328890--espanso-capdacoverride/espanso-capdacoverride.nix, systems/espanso/nixpkgs-328890--espanso-capdacoverride/wrapper-lib.c
Espanso does various things that are bad if we don't get permission
- Making a window on first startup
- Requiring configuration or there will be an error window
- Needing some "interesting" capability/permission hacks
Given not everyone will necessarily want this, and that it has quite
high potential to cause trouble, we shouldn't be putting it even in
personal - let's give it its own ingredient
---
I've pulled in some hacks from https://github.com/NixOS/nixpkgs/pull/328890 to correct the
capabilities here. Without it, espanso required setting some permissions
on /dev/uinput and adding the running user to the "input" group, which
is a much worse hack
=> some espanso fixes

homes/niri/default.nix, homes/niri/niri.nix, homes/niri/swaync.nix
previously niri was running directly as `niri --session`, however this
seems to cause some race conditions for some dbus services (e.g. our
notifications daemon starting in a different session to niri, stopping
us from opening it)
we can solve this by tying the graphical start target to niri starting,
and using niri-session to start niri. Without `-l` on `niri-session`
niri appears to freeze - it seems like the `-l` starts another login
shell, I'm not sure why it's necessary (and it doesn't seem to be
necessary when running niri interactively)
---
all this in aid of adding swaync...
swaync is a notification daemon - so finally we can stop Firefox, etc.
from creating its own windows and get notifications from things like
Thunderbird
last iteration we had problems with mako, so we were …
=> feat: add swaync

homes/coded/default.nix, homes/coded/keyboard.nix, homes/espanso/espanso.nix
When you didn't have a keyboard layout set you would try to set values from a null
We erroneously changed from an inherit here in an attempt to avoid the problem, however the real change is to avoid setting the keyboard options at all if you haven't specified anything.
This is the same as we do in niri
=> fix: prevent espanso build failure

homes/minion/espanso.nix
Previously I incorrectly had backslashes in speech marks, which were getting dropped by attempting to escape the next characters
I additionally made a typo in my email once, which I have also corrected
=> fix(minion): correct espanso matches

systems/niri/niri.nix
Previously we were fetching various things to evaluate our configuration
Some of it was collabora-gtimelog, which I removed by adding it to npins
The remainder was niri cargo lock dependencies, which are a little harder to fix. This said, we are currently tracking unstable niri which we don't really need to be doing: I've read through the changes from niri v25.05.1...main and I don't believe that any of them are important to us at the moment
Therefore, tracking nixpkgs niri fixes this for us
---
When niri gets significant updates we may want to revisit whether to use nixpkgs unstable on our systems/fetch only niri from unstable/etc.
=> fix: eliminate fetching for eval

systems/saurosuchus/hardware.nix
Using Yubikey for LUKS requires this option to be enabled.
=> fix(saurosuchus): enable systemd for initrd

homes/niri/niri.nix
Previously if using tap to click niri would follow 1-2-3 finger tap methods however if actually clicking would follow button areas, we believe this inconsistoncy is more bugful
=> fix(niri): Disable button areas on trackpad

homes/minion/espanso.nix
Previously I was accidentally using the "non-word character" regex class rather than the whitespace class. This led to sky@a. causing a menu to choose between these two. Let's fix that...
=> fix(minion): correct sky@a espanso regex

.github/workflows/tangled.yml
We're interested in using tangled in the future due to its nicer stacked PR workflow than GitHub, though we will need CI to properly make the jump. Nevertheless, we believe it's worth mirroring our main/release branches over to tangled now so that anyone who wants to can pull from there
=> ci: add tangled.sh mirror

homes/development/collaboration.nix
PacketMix uses Helix as its main editor - let's set the Helix bindings in Zed too
From https://github.com/zed-industries/zed/issues/4642, Zed 0.193 and above have had the option to change to a Helix normal mode that will work more like what we're familiar with. Zed 0.193 is only in unstable so let's switch there for now too...
=> feat(zed): switch to helix mode

homes/niri/niri.nix
When held down, this bind causes a rapid open/close of the overview, which is both useless and uncomfortably-flickery. Turning off repeat fixes this
=> fix(niri): do not repeat overview open bind

homes/niri/quickshell/shell.qml
Quickshell is currently too big for us to really add other widgets, so it would make more sense to shrink it - here we use something that's akin to css' vmin to decide how tall the area should be.
We decided to anchor the area to the top of the window (rather than the center of the available area). Without doing so the bar looks weird when we have the top workspace focused (i.e. a lot of the time). It's also meant to be some sort of a bar-like thing (so anchoring it makes sense).
=> feat: make quickshell smaller on vertical monitors

homes/niri/niri.nix
This is useful for tricking video sites into thinking that you have maximized your window, say
=> feat(niri): Add windowed-fullscreen bind

homes/catppuccin/catppuccin.nix, homes/common/default.nix, homes/common/gtk.nix
We currently have various gtk apps that don't have an icon theme, which means they show broken icons...
Also: It turns out that the catppuccin gtk theme is deprecated (why it's not on by default) and depends on gtk being enabled *anyway*, so best to remove that line from our configuration as it was a no-op
=> fix(gtk): add icon theme

homes/development/default.nix, homes/development/jujutsu.nix, systems/personal/configuration.nix
Meld has some problems with diff editing
- Permissions become scuffed when you use copy from one place to another
- There's no real way to undo or get both sides - it's very barebones
Therefore, let's install the (more complex, unfortunately) kdiff3 for
use as a diff tool instead. We may want to change configuration on this
later to autoselect something different from its default "merge" option
and auto-un-collapse folders, presuming these are configurable
We also don't tend to use meld for resolving conflicts, so let's
install the mergiraf tool to add some value to `jj resolve` over manual
resolution
=> feat(jujutsu): change diff/merge tools

homes/niri/niri.nix
We're using a lot of time/space building niri, but actually we are only using the version from nixpkgs anyway because we aren't using standalone homes beyond a CI build - let's stop wasting resources
=> fix(niri): use same package for system and home

npins/sources.json, packages/beancount-autobean/default.nix, packages/beancount-beancount_plugin_utils/default.nix, packages/beancount-beancount_share/default.nix, packages/beancount-smart_importer/default.nix, packages/default.nix, systems/teal/acme.nix, systems/teal/default.nix, systems/teal/fava.nix, systems/teal/fava/minion/truelayer.py, systems/teal/headscale.nix, systems/teal/packetmix.nix, systems/teal/secrets.nix, systems/teal/silverbullet.nix
We previously had various stuff running on teal from Infra/NixFiles
We've adapted our modules to work outside that environment (many of them depended on overly-complex clicks constructs) and moved them over so we can start deploying teal from PacketMix
=> init(teal): add modules

systems/teal/default.nix, systems/teal/stalwart.nix
We've been using mailcow as a mailserver on midnight for a long while,
but that is dockerized.
We've also used mailu which has the same problem. Stalwart is the first
example we've seen of a mailserver that is configurable in nix and
yet has the option to configure some things (such as users) via a web
dashboard.
=> feat(teal): add stalwart

systems/teal/default.nix, systems/teal/vaultwarden.nix
As part of our ongoing effort to migrate off the old midnight config, we are moving our vaultwarden server to teal. The config here is largely the same. We are, however, on a higher stateVersion making the storage path change.
Additionally, we handle secrets rather differently - notably:
- postgresql is now connecting over a local socket so does not need a password
- everything else is split over two environment files: a secret one (manually created in /secrets) and a regular one (created by the nix module using the normal settings options)
=> feat(teal): migrate vaultwarden

systems/freshlybakedcake+personal/dav.nix, systems/freshlybakedcake+personal/default.nix
After we set up stalwart we now have it as a webdav mount for file sharing. Let's set up some code to mount it by default
If you don't do this, you'll get a "no such device" error when you attempt to access /mnt/freshly. As the automount doesn't do anything until you attempt to use the folder you won't get an error beforehand
Finally, this does mean that you may not want to mount directly over /mnt - it doesn't stop you from doing so but that will then shadow this mount
=> feat: add davfs2

npins/sources.json
Stalwart needs intervention to upgrade so it is preventing our automated npins dependency bump... for now, let's disable it upgrading automatically
=> chore: freeze stalwart

homes/niri/default.nix, homes/niri/ssh.nix
Since switching niri to a systemd service we have gained some problems with ssh-agent: it needs a restart to work.
We can't trivially pull niri later since gnome-keyring ssh wants to be started as part of graphical-session-pre and depends on ssh-agent. To fix this we can disable the gnome-keyring ssh module.
=> fix(niri): start ssh-agent later

npins/sources.json, packages/default.nix, packages/lua-multipart/default.nix, systems/teal/copyparty.nix, systems/teal/default.nix, systems/teal/fava.nix, systems/teal/silverbullet.nix
We've used Stalwart for files for a few days, and it is becoming clear that there are some problems for our use-case:
- Some clients we want to use don't support ACLs (see stalwartlabs/stalwart#1927)
- There's no way to do file sharing with anyone who we don't give a mail account
- Webdav is the only supported protocol (again, causing some trouble getting files on all devices)
Therefore we're trialing Copyparty. If it goes well, we'll block the /dav/file endpoint of Stalwart and switch over entirely
=> feat(teal): add Copyparty

systems/teal/copyparty.nix
Our lua parsing code has been broken when our multipart content can't be properly parsed: we've been getting errors like
Aug 06 06:10:35 teal nginx[2647]: 2025/08/06 06:10:35 [error] 2647#2647: *4021 lua entry thread aborted: runtime error: access_by_lua(...ymhfpmsjqja9dc7k4pp9v54rc5z-nginx.conf:87):16: attempt to index a nil value
Aug 06 06:10:35 teal nginx[2647]: stack traceback:
Aug 06 06:10:35 teal nginx[2647]: coroutine 0:
Aug 06 06:10:35 teal nginx[2647]:         access_by_lua(...ymhfpmsjqja9dc7k4pp9v54rc5z-nginx.conf:87): in main chunk while sending to client, client: 192.168.0.6, server: files.freshly.space, request: "GET /ws/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1", host: "71.246.21.254"
which we believe to be due to trying to read failed parsing (though we …
=> fix(copyparty): correct error on upload

systems/common/packetmix.nix, systems/teal/default.nix, systems/teal/packetmix.nix
Previously the only impermanence stuff for packetmix was in teal. It should instead be in common as we now have systems that are not teal which are impermanent
=> fix(packetmix): move impermanence into common

systems/common/default.nix, systems/common/ulimit.nix
I'm having trouble building LibreOffice and Collabora since adding impermanence... my best guess is maybe impermanence uses more files than having it off - e.g. for FUSE?
Since `ulimit -n 65535` fixes the issue, it's probably worth making this permanent
If you try to do this, the first thing you'll find is `pam.loginLimits` buuuuuut that isn't actually respected, it turns out, as the systemd default overrides it (you can still manually override the limit but that is annoying). Oh well, got there eventually
=> feat: increase soft file limit

systems/marbled/hardware-configuration.nix
Marbled was failing to use a USB mouse with the docking port; enable bolt to allow the docking port to be authorised.
=> fix(marbled): enable bolt

homes/minion/default.nix, homes/minion/xdg.nix
I want to use firefox as my default browser. Since switching to impermanence I haven't been saving my default apps and they have been decaying on every reboot. As there is hm-options for it, I should just be using those.
=> feat(minion): set default browser

systems/teal/default.nix, systems/teal/midnight.nix
We're going to switch over from sending traffic to midnight to sending it to teal. We still have a couple of things on midnight that we need to keep for a short amount of time. Therefore, we need to add routes back to them from teal to keep them running for now...
=> feat(teal): add routes to midnight

.github/workflows/eval.yml, .github/workflows/nixos.yml, .github/workflows/treefmt.yaml, .github/workflows/update-npins.yml, ci.nix, inputs.nix, lib/default.nix, nilla.nix, npins/sources.json, systems/teal/stalwart.nix
We've kept stalwart pinned at 0.13.0 for a little while since as we
needed some features from it before nixpkgs had it. Nixpkgs is now on
0.13.2, so we should be using it instead. We don't want to upgrade just
to 0.13.2 though, since as we are paying for stalwart enterprise - let's
use enterprise stalwart when we're not in CI.
=> feat: upgrade stalwart

systems/teal/copyparty.nix
This is a regression from upuvkmrlstxkxpptssslvyrvvwnwosmt (commit 4de3921b846818357f0b79960b575b7db3f71043)
In it, we changed the default listener IP to include tailscale IPs, but this meant that the main copyparty listener was used rather than the tailscale-authed one. Explicitly specifying that the tailscale-authed listener should listen on the tailscale IP and that the main listener should only listen on 0.0.0.0 fixes this.
=> fix(copyparty): make tailscale auth work again

systems/teal/headscale.nix
If headscale has an email for a user, it'll use the local part as the username. This wasn't a problem when that was the same but as we're making some users' primary emails not have their username as the local part (e.g. minion@clicks.codes -> sky@a.starrysky.fyi) this is now causing trouble
=> fix(headscale): stop requesting email scope

homes/niri/default.nix, homes/niri/niri.nix, homes/niri/scriptfs.nix
When I added scriptfs, I incorrectly started it similarly to xdg-desktop-portal. Instead, I meant to start it like we do the ssh-agent: both exclusively WantedBy and After niri. This avoids the start loop with systemd secrets stuff...
=> fix(scriptfs): break starting loop

homes/espanso/espanso.nix
I have some matches that I want to control out-of-band on PacketMixed machines:
- Matches that can't be placed in a public GitHub repository
- Espanso hub packages which I want to install without controlling them in PacketMix
While the recommended method for adding matches is still PacketMix config - after all, your matches can't follow you/etc. if they aren't updated along with your system - we may as well give impermanence users like myself the choice to install matches imperatively also
=> feat(espanso): persist matches directory

homes/niri/quickshell.nix
When we implemented ingredients, we accidentally left quickshell in a subdirectory where it'd never be used...
...that led to our overview background, time and battery indicators being missing since as the code to display them was never imported...
...oops
=> fix(quickshell): move out of subdirectory

systems/teal/josh.nix
Josh is a git proxy for working with monorepos - it lets you filter out large portions of your repository so you can clone just the project you are working on
We'd like to try using a monorepo (patisserie) when we move to tangled, and as part of that we'd like to use Josh with it... let's add it!
=> feat(teal): add josh

homes/default.nix, homes/nightshift/gammastep.nix, systems/default.nix, systems/nightshift/geoclue2.nix
I often use computers fairly late - it's nice to have my display turn a little less blue at night. Here's an ingredient to do that!
I considered having this as some sort of 'nightshift+niri', since as I am using gammastep which is wayland only, but then I realized that all supported desktop systems use wayland so it doesn't really matter. If someone uses an X system later they may want to factor this out...
The fact that nightshift relies on system geoclue2 is yet another nail in the "we should be determining system ingredients from your homes" coffin...
=> feat: add nightshift

homes/redhead/misc.nix
I continually end up installing this one to mess with my laptop brightness... probably worth just installing it in a misc.nix. I don't want to use homes/minion/misc.nix since as I don't *use* it on emden, so best to just give redhead a misc of its own...
=> feat(minion): add brightnessctl

LICENSES/BSD-3-Clause.txt, npins/sources.json, packages/default.nix, packages/headscale/default.nix, packages/headscale/deferred-auth.patch, packages/headscale/deferred-auth.patch.license, systems/teal/headscale.nix
When we start up headscale, it tries to connect to OIDC. If our OIDC server is down, there were previously two options:
- We can fail to start the server altogether
- We can fallback to CLI auth and lose the ability to use OIDC until headscale is restarted
Neither of these are what I want: I want us to start up anyway but not allow registration until OIDC successfully connects
I've made a patch to do just that! I made it ontop of main, so I've also had to upgrade headscale to allow use of this patch.
I had some troubles with nilla, which can't properly interpret the headscale flake (missing rev/shortRev attributes) - therefore I've taken the nix package definition from the headscale repo and updated it to use the patch and the correct source manually
Refs: juanfont/headscale#1873
=> feat(headscale): defer auth to device registration
